server:
  port: 8081
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: 12345678
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 357945980977-jqstfbmkhmbf18q9m6dbk4b7i35vgi73.apps.googleusercontent.com
            client-secret: XpCDWfkvlR4euqJyAYVQEN-0
            scope: 
            - email
            - profile
          facebook:
            client-id: 203401501605135
            client-secret: 9b067c6f2383b5185711ffe8dbbe1f63
            scope: 
            - email
            - public_profile
  thymeleaf:
    suffix: .html
